<!DOCTYPE html>
<html>
<head>
	<title>Everybody Welcome</title>
	<style>
		body {
			background-color: gray;
		}
	</style>
</head>
<body>
<header>
    <h1>Everybody Welcome</h1>
    
</header>




<main>
    
    <p>There are one billion people in the world with additional access needs, including over 14 million disabled
people in the U.K.</p>
<p>93% will search for access information about your venue before they visit and, if they can’t find what they
are looking for, 41% will take their business elsewhere meaning that you could be missing out on valuable
custom just for the sake of providing relevant information.</p>
<p>But what information should you provide? How should you provide it, when should you promote it and
where?</p>
<p>Everybody Welcome is the easy way to share your accessibility information and welcome the world.</p>
<p>So what are you waiting for?</p>

<h2> More information</h2>

<h3>What is Everybody Welcome?</h3>
<p>Everybody Welcome is a straightforward, smart tool to help you record, share and market relevant
accessibility information about your venue.</p>

<h3>Why is it needed?</h3>

<p>Research shows that more than half of disabled people are not confident about visiting new places and that
79% have had a disappointing trip or had to change their plans at the last minute due to poor accessibility.
77% also find that accessibility information hard to find or inaccurate. (*Source: Euan’s Guide Access Survey 2019) </p>

<p>Venues, on the other hand, are unsure what information provide or find existing methods of providing
access information costly, complicated or time-consuming so often provide nothing. </p>

<p>As a result, people with additional access needs are missing out on visits and experiences and businesses
are missing out on the additional income that would be generated by those visits.   </p>

<p>Everybody Welcome is designed to change that by supporting businesses to provide relevant accessibility
information easily and quickly and enabling consumers to plan visits with ease. </p>
 
<h3>What do I need to do? </h3>

<p>Simply answer a short series of questions about your business, venue or service, add some images and in
just a few clicks you have a handy, accurate accessibility summary that you can share on your website, in
your social media or anywhere else that takes your fancy!</p>

<h3>What do I get?</h3>

<p>Not only does creating an Everybody Welcome listing give you a unique URL to share with your target
audiences, it also generates an exclusive QR code to display around your venue, enabling you to provide
access information for your visitors when and where they need it.</p>

<p>Your Everybody Welcome listing also links back to your own website, ensuring that visitors who need
additional information know exactly where to find it.</p>

<p>Each listing is included in our free to use directory which enables potential visitors to search for venues by
location, type or accessibility features, leading to better experiences for visitors and increased footfall and
revenue for you.</p>

<p>If you want to dig a little deeper, our Access Tracker self-audit tool will enable to you to audit the
accessibility of your offering in more detail, providing information and tools to support you in creating an
action plan for improvement.</p>

<h3>How much does it cost?</h3>

<p>Everybody Welcome is free to use and includes listing in the Directory for one year. At the end of each year,
you will be prompted to check the accuracy of your listing before it renews, giving you the opportunity to
make changes and giving visitors confidence that the information provided is current, relevant and
accurate</p>

<p>For those who want to take their accessibility to the next level, our Access Tracker tool is available at just
£XXXX per year.</p>
<h3>Where do I start?</h3>
<p>Simply grab a cuppa, click on the link below and you’re good to go! Get ready to welcome the world….</p>
<h4>Get ready to make Everybody Welcome!</h4>
</main>





<footer>
    <p>&copy; Everybody Welcome</p>
</footer>
</html>